[project]
name = "json-to-prompt"
version = "0.1.0"
description = ""
authors = [
    {name = "joegasewicz",email = "joegasewicz@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[tool.poetry]
packages = [{include = "json_to_prompt", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
